version: "3.6"
services:
    postgres:
        image: postgres:15
        container_name: kem_postgres
        environment:
            POSTGRES_PASSWORD: kapila
            POSTGRES_DB: kapila_expense_management
        ports:
            - "5430:5432"
        restart: always
        volumes:
            - ./postgresql:/var/lib/kapila_expense_management/postgresql/data
    hasura:
        image: hasura/graphql-engine:v2.35.1
        # image: hasura/graphql-engine:v2.35.1-ce.cli-migrations-v2
        container_name: kem_hasura
        depends_on:
            - "postgres"
        restart: always
        ports:
            - "8081:8080"
        environment:
            HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:kapila@postgres:5432/kapila_expense_management
            HASURA_GRAPHQL_ADMIN_SECRET: kapila
            HASURA_GRAPHQL_JWT_SECRET: '{"type": "HS256", "key": "kapila-expense-management-1234567", "claims_namespace_path": "$.hasura.claims"}'
            SERVER_BASE_URL: http://host.docker.internal:4001
            SERVER_SECRET: kapila-expense-management-123
        volumes:
            - ./hasura/migrations:/kapila_expense_management/hasura-migrations
            - ./hasura/metadata:/kapila_expense_management/hasura-metadata
